Added "sudo"
At least on my Ubuntu, I got the following Error messages 

ERROR: Couldn't connect to Docker daemon at http+docker://localunixsocket - is it running?
If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.

if I didn't use sudo with docker-compose. 

But feel free to reject my commit if this is only due to my specific setting